<h1>Machine Learning - Assignment 1<h1>

In [19]:
import pandas as pd
import numpy as np

In [20]:
#Function to display the output on the console and also write the output to a text file output.txt
def ProcessOutputToFile(data):
    print(data)
    f = open("output.txt", "a+")
    f.write(data + '\n')
    f.close()

<b>TRAINING using the spambasetrain.csv dataset</b>

In [21]:
#We will load all the data from the training set into a data frame and assign them labels
basedf = pd.read_csv('spambasetrain.csv', names=['char_freq_;', 'char_freq_(', 'char_freq_[', 'char_freq_!', 'char_freq_$', 'char_freq_#', 'capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total', 'ClassLabel'])

#We just display the first 4 records of the training data set
basedf.head()

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
0,0.0,0.316,0.0,0.000,0.000,0.000,1.125,2,9,0
1,0.0,0.735,0.0,0.735,0.000,0.000,2.571,10,18,0
2,0.0,0.105,0.0,0.000,0.158,0.000,1.494,10,139,1
3,0.0,0.299,0.0,0.000,0.000,0.199,2.465,28,106,1
4,0.0,0.000,0.0,0.817,0.000,0.000,1.857,15,39,0

In [22]:
#Filter out the training dataset and just store all the data from the training set with Class Label 1 into a new training set
#known as dfClass1
dfclass1 = basedf[(basedf['ClassLabel'] == 1)]
dfclass1.head()

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
2,0.0,0.105,0.0,0.000,0.158,0.000,1.494,10,139,1
3,0.0,0.299,0.0,0.000,0.000,0.199,2.465,28,106,1
8,0.0,0.075,0.0,0.613,0.532,0.137,7.300,763,2453,1
10,0.0,0.204,0.0,0.204,0.127,0.102,2.962,73,400,1
13,0.0,0.000,0.0,0.000,0.000,0.000,2.083,7,25,1

In [23]:
dfclass0 = basedf[(basedf['ClassLabel'] == 0)]
dfclass0.head()

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
0,0.000,0.316,0.0,0.000,0.0,0.000,1.125,2,9,0
1,0.000,0.735,0.0,0.735,0.0,0.000,2.571,10,18,0
4,0.000,0.000,0.0,0.817,0.0,0.000,1.857,15,39,0
5,0.000,0.000,0.0,2.272,0.0,0.000,1.750,7,14,0
6,0.055,0.334,0.0,0.055,0.0,0.055,1.685,6,59,0

In [24]:
dfclass1_Calc = dfclass1.describe()
dfclass1_Calc

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
count,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.0
mean,0.020247,0.103439,0.007847,0.491662,0.173151,0.084901,9.496347,97.209129,453.512863,1.0
std,0.086846,0.179286,0.049154,0.740130,0.360521,0.726143,54.460853,190.709179,783.697723,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,1.0
25%,0.000000,0.000000,0.000000,0.088000,0.000000,0.000000,2.302000,15.000000,94.000000,1.0
50%,0.000000,0.067000,0.000000,0.309000,0.079000,0.000000,3.571000,38.000000,194.000000,1.0
75%,0.000000,0.145000,0.000000,0.615000,0.211000,0.017000,5.634000,82.000000,533.000000,1.0
max,0.768000,4.271000,1.171000,7.843000,6.003000,19.829000,1102.500000,2204.000000,15841.000000,1.0

In [25]:
dfclass0_Calc = dfclass0.describe()
dfclass0_Calc

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
count,1794.000000,1794.000000,1794.000000,1794.000000,1794.000000,1794.000000,1794.000000,1794.000000,1794.000000,1794.0
mean,0.048426,0.157487,0.016960,0.110713,0.011503,0.025892,2.376590,18.182274,164.143255,0.0
std,0.297163,0.264915,0.069609,0.646210,0.063876,0.298779,6.119418,43.763761,379.650061,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.0
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.350000,4.000000,18.000000,0.0
50%,0.000000,0.064000,0.000000,0.000000,0.000000,0.000000,1.824000,10.000000,53.000000,0.0
75%,0.000000,0.224000,0.000000,0.028500,0.000000,0.000000,2.532000,18.000000,137.000000,0.0
max,4.367000,5.277000,1.449000,19.131000,0.903000,7.407000,251.000000,1488.000000,5902.000000,0.0

<b>Calculate the Prior for Both Class 0 and Class 1</b>

In [26]:
priorOfClass0 = (dfclass0['ClassLabel'].count())/(basedf['ClassLabel'].count())
ProcessOutputToFile("Prior for Class 0 [P(C=0)] = " + str(priorOfClass0))

Prior for Class 0 [P(C=0)] = 0.5981993998

In [27]:
priorOfClass1 = (dfclass1['ClassLabel'].count())/(basedf['ClassLabel'].count())
ProcessOutputToFile("Prior for Class 1 [P(C=1)]  = " + str(priorOfClass1))

Prior for Class 1 [P(C=1)]  = 0.4018006002

<b>Calculate the Mean and Variance for both class 0 and class 1</b>

In [28]:
mean_for_class0 = {}
mean_for_class1 = {}

variance_for_class0 = {}
variance_for_class1 = {}

dfCols =['char_freq_;', 'char_freq_(', 'char_freq_[', 'char_freq_!', 'char_freq_$', 
        'char_freq_#', 'capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total']

#function to calculate the mean for all the attributes of a given class
def calculateMean(meandict, classDf):
    for mail_attribute in dfCols:
        currSum = 0
        
        for index, row in classDf.iterrows():
            currSum += row[mail_attribute]
        
        meandict.update({mail_attribute : (currSum)/classDf[mail_attribute].count()})
        
#function to calculate the variance for all the attributes for a given class
def calculateVariance(varianceDict, meanDict, classDf):
    for mail_attribute in dfCols:
        currVar = 0
        
        for index, row in classDf.iterrows():
            currVar += np.power((row[mail_attribute] - meanDict[mail_attribute]), 2)
        
        varVal = currVar/(classDf[mail_attribute].count() -1 )
        varianceDict.update({mail_attribute : varVal})
        
    
#calculate mean for class 0
calculateMean(mean_for_class0, dfclass0)

#calculate mean for class 1
calculateMean(mean_for_class1, dfclass1)

#calculate variance for class 0
calculateVariance(variance_for_class0, mean_for_class0, dfclass0)

#calculate variance for classs 1
calculateVariance(variance_for_class1, mean_for_class1, dfclass1)

ProcessOutputToFile("Mean for class 0 " + str(mean_for_class0))
ProcessOutputToFile("variance for class 0 " + str(variance_for_class0))
ProcessOutputToFile("Mean for class 1 " + str(mean_for_class1))
ProcessOutputToFile("variance for class 1 " + str(variance_for_class1))

Mean for class 0 {'char_freq_;': 0.048425863991081425, 'char_freq_(': 0.15748662207357839, 'char_freq_[': 0.016959866220735784, 'char_freq_!': 0.11071293199554071, 'char_freq_$': 0.011502787068004453, 'char_freq_#': 0.025892419175027874, 'capital_run_length_average': 2.3765897435897418, 'capital_run_length_longest': 18.182274247491637, 'capital_run_length_total': 164.14325529542921}
variance for class 0 {'char_freq_;': 0.088305603257061979, 'char_freq_(': 0.070179774779101339, 'char_freq_[': 0.0048453525434288824, 'char_freq_!': 0.41758787460121027, 'char_freq_$': 0.0040801330095175435, 'char_freq_#': 0.089268879105915813, 'capital_run_length_average': 37.447270639180786, 'capital_run_length_longest': 1915.2668133413704, 'capital_run_length_total': 144134.16853507495}
Mean for class 1 {'char_freq_;': 0.020247302904564311, 'char_freq_(': 0.10343900414937772, 'char_freq_[': 0.0078473029045643145, 'char_freq_!': 0.49166224066390096, 'char_freq_$': 0.1731510373443983, 'char_freq_#': 0.084901244813278071, 'capital_run_length_average': 9.496346887966812, 'capital_run_length_longest': 97.209128630705393, 'capital_run_length_total': 453.51286307053942}
variance for class 1 {'char_freq_;': 0.0075422809831680992, 'char_freq_(': 0.032143331201665272, 'char_freq_[': 0.002416074670875807, 'char_freq_!': 0.54779209761789971, 'char_freq_$': 0.12997566487641313, 'char_freq_#': 0.52728327678416864, 'capital_run_length_average': 2965.9844858446845, 'capital_run_length_longest': 36369.991112612159, 'capital_run_length_total': 614182.12047393771}

<b>TESTING using the spambasetest.csv</b>

In [29]:
#Load the test data from spambasetest.csv into a dataframe
testDf = pd.read_csv('spambasetest.csv', names=['char_freq_;', 'char_freq_(', 'char_freq_[', 'char_freq_!', 'char_freq_$', 'char_freq_#', 'capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total', 'ClassLabel'])
testDf.head()

,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,ClassLabel
0,0.000,0.000,0.00,0.000,0.000,0.0,2.000,4,6,0
1,0.000,0.000,0.00,0.102,0.000,0.0,2.531,30,81,0
2,0.000,0.492,0.00,0.000,0.000,0.0,1.890,11,138,0
3,0.203,0.195,0.05,0.000,0.014,0.0,2.880,45,1080,0
4,0.000,0.000,0.00,0.874,0.000,0.0,5.114,107,179,1

In [30]:
#Function to calculate the gaussian distribution for a given attribute with a given mean and standarad deviation


def calcGaussianDist(x, mean, variance):
    val = (1/np.sqrt(2 * np.pi * variance)) * (np.exp((-1 * np.power(x - mean, 2)) / (2 * variance)))
    return val 

#Function to calculate the sum of all the PDFs of all the attributes for a given class
def calcEstPdf(row, meanList, varList):
    val=0
    for attrName in dfCols:
        attrGauss = calcGaussianDist(row[attrName], meanList[attrName], varList[attrName])
        val = val + np.log(attrGauss)
        
    return val

#List to store the results of all the predictions made
predictedResultSet=[]

#Counter to maintain the count of all the correct results predicted
correct=0

#Counter to maintain the count of all the results predicted incorrectly 
error=0

#Iterate thru the list of all the test cases to predict labels using naive bayes gaussian
for index, row in testDf.iterrows():
    #Calculate the estimated pdf for the given example for Class 0
    estPDFClass0 = calcEstPdf(row, mean_for_class0, variance_for_class0) + np.log(priorOfClass0)
    
    #Calculate the estimated pdf for the given example for Class 1
    estPDFClass1 = calcEstPdf(row, mean_for_class1, variance_for_class1) + np.log(priorOfClass1)
    
    #Calculate the class of the given example based on the estimated pdfs
    if (estPDFClass0 > estPDFClass1):
        classL = 0 
    else: 
        classL = 1
    
    #print("class 0 : " + str(estPDFClass0) + " class 1: " + str(estPDFClass1) + " Pred : "  + str(classL))
    
    #Check if the expected label for the given class and the  calculated label for the given class are 
    #the same, if not then we will count that as an error.
    if (row['ClassLabel'] == classL):
        correct = correct+1;
    else:
        error = error+1;
    
    #Store the predicted result for the given example in the result
    predictedResultSet.append(classL)

In [31]:
ProcessOutputToFile("Predicted class for all test Examples : " + str(predictedResultSet))

Predicted class for all test Examples : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [32]:
ProcessOutputToFile("Total Number of test examples classified correctly :  " + str(correct))
ProcessOutputToFile("Total Number of test examples classified incorrectly :  " + str(error))

Total Number of test examples classified correctly :  160
Total Number of test examples classified incorrectly :  40

In [33]:
#Calculate the percentage of error on test examples
errorPercentage = ((error) / (error+correct))*100

#Calculate the percentage of results predicted correctly
correctPercentage = ((correct)/ (error+correct)) * 100

In [34]:
ProcessOutputToFile("Percentage of error on the test examples : " + str(errorPercentage) + "%")
ProcessOutputToFile("Percentage of results predicted correctly on test examples : " + str(correctPercentage) + "%")

Percentage of error on the test examples : 20.0%
Percentage of results predicted correctly on test examples : 80.0%

<h3> Calculation for finding accuracy using Zero-R </h3>

In [35]:
'''
Incase if we are using the Zero-R method for predictions, based on our prior calculations
we find that the prior for P(C) for c=0 i.e 0.5981993998 is greater than the P(C) for c=1 
i.e 0.4018006002. Thus, based on Zero-R our classifier Class 0 for all the given test examples.
Therefore it will predict class for all the examples as class 0
'''

#However, we find that the based on the test dataset provided, the actual predictions for class zero were supposed to be
#just 118.
c0 = testDf[(testDf['ClassLabel'] == 0)]

#it will predicted all the samples as class 0 using zero-R , thus the total examples predicted as zero as
resultsPredictedCount = testDf['ClassLabel'].count() 

#Actual count of the predicted results as class zero is supposed to be as below
resultsActuallyPredictedForGivenClass = c0['ClassLabel'].count()

#Therefore, error in predcited results is as below
errorPredict = resultsPredictedCount - resultsActuallyPredictedForGivenClass
correctPredict =  resultsPredictedCount - errorPredict

print("Error in  prediction using zero-R is : "  + str((errorPredict/(errorPredict+correctPredict)) * 100) + "%")

#Thus, the accuracy of the given zero-r can be calculated using the below formula
accuracy = (correctPredict/ (errorPredict+correctPredict)) * 100
print("Accuracy of Zero-R method is : " + str(accuracy) + "%")

Error in  prediction using zero-R is : 41.0%
Accuracy of Zero-R method is : 59.0%